from __future__ import annotations

from src.genai_signals import analyze_repo
from src.models import Commit, IngestResult, RepoSpec


def _commit(
    sha: str,
    author: str,
    message: str,
    files_changed: list[str],
    timestamp: str,
) -> Commit:
    return Commit(
        sha=sha,
        author=author,
        email=f"{author.lower()}@example.com",
        timestamp=timestamp,
        message=message,
        files_changed=files_changed,
    )


def _result(commits: list[Commit]) -> IngestResult:
    return IngestResult(
        spec=RepoSpec(team="Team Test", repo_url="https://github.com/org/repo"),
        commits=commits,
    )


def _signal_names(report) -> set[str]:
    return {signal.name for signal in report.genai_signals}


def _human_signal_names(report) -> set[str]:
    return {signal.name for signal in report.human_signals}


def test_large_single_commit_detected() -> None:
    commits = [
        _commit(
            "a1",
            "Alice",
            "initial scaffolding",
            [f"file_{i}.py" for i in range(16)],
            "2026-02-20T14:00:00Z",
        )
    ]

    report = analyze_repo(_result(commits))

    assert "large_single_commit" in _signal_names(report)


def test_genai_attributed_commit_detected() -> None:
    commits = [
        _commit(
            "b1",
            "Alice",
            "Generated by ChatGPT for API handlers",
            ["src/api.py"],
            "2026-02-20T14:00:00Z",
        )
    ]

    report = analyze_repo(_result(commits))

    assert "genai_attributed_commit" in _signal_names(report)


def test_multiple_authors_detected() -> None:
    commits = [
        _commit("c1", "Alice", "start", ["src/app.py"], "2026-02-20T14:00:00Z"),
        _commit("c2", "Bob", "refactor", ["src/app.py"], "2026-02-20T15:00:00Z"),
    ]

    report = analyze_repo(_result(commits))

    assert "multiple_authors" in _human_signal_names(report)


def test_fixup_commits_detected() -> None:
    commits = [
        _commit("d1", "Alice", "initial", ["src/app.py"], "2026-02-20T14:00:00Z"),
        _commit("d2", "Alice", "fix typo in handler", ["src/app.py"], "2026-02-20T15:00:00Z"),
    ]

    report = analyze_repo(_result(commits))

    assert "fixup_commits" in _human_signal_names(report)


def test_no_signals_produces_clean_report() -> None:
    commits = [
        _commit("e1", "Alice", "feat api", ["src/api.py"], "2026-02-20T14:00:00Z"),
        _commit("e2", "Alice", "add tests", ["tests/test_api.py"], "2026-02-20T15:00:00Z"),
    ]

    report = analyze_repo(_result(commits))

    assert report.genai_signals == []
    assert report.human_signals == []
    assert report.summary == "No GenAI usage signals detected."


def test_summary_reflects_signal_combinations() -> None:
    signals_with_human = [
        _commit(
            "f1",
            "Alice",
            "generated by model",
            [f"src/file_{i}.py" for i in range(11)],
            "2026-02-20T14:00:00Z",
        ),
        _commit("f2", "Bob", "fix bug in file_1", ["src/file_1.py"], "2026-02-20T15:00:00Z"),
    ]
    report_with_human = analyze_repo(_result(signals_with_human))
    assert report_with_human.summary == "GenAI usage detected with evidence of human review."

    signals_without_human = [
        _commit(
            "g1",
            "Alice",
            "generated by helper",
            [f"src/gen_{i}.py" for i in range(11)],
            "2026-02-20T14:00:00Z",
        )
    ]
    report_without_human = analyze_repo(_result(signals_without_human))
    assert report_without_human.summary == (
        "GenAI usage detected with limited evidence of human engagement."
    )
